from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent
MODELS_DIR = BASE_DIR / "models"
DASHBOARD_PAYLOADS_PATH = MODELS_DIR / "dashboard_demo_payloads.pt"
WEIGHT_DELAY = 0.50
WEIGHT_LATE = 0.30
WEIGHT_RESCHEDULES = 0.20
HIGH_PROCRASTINATION_THRESHOLD = 0.60
CHRONIC_RATIO_THRESHOLD = 0.65
EMERGING_RATIO_THRESHOLD = 0.30
HOST = "127.0.0.1"
PORT = 8000
