[project]
name = "academic-procrastination"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.142.2",
    "greenlet>=3.5.6",
    "langchain>=1.4.3",
    "sqlalchemy>=2.1.3",
]
